# Attrition Prediction Model

%pip install scikit-learn

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('../data/hr_synthetic_dataset.csv')
df

,EmpID,Department,Position,JobLevel,ManagerID,RecruitmentSource,Gender,DateofBirth,Salary,DateofHire,...,EmploymentStatus,TermReason,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,DaysLateLast30,Absences,OvertimeHoursPerMonth,YearsSinceLastPromotion
0,10001,Production,Production Technician II,2,PRD-M3,Company Website,Male,1976-01-04,45100,2011-07-06,...,Active,NaN,Fully Meets,3.89,4,2,0,8,19,2.4
1,10002,Production,Production Lead,4,PRD-M2,Google Search,Female,1974-12-25,57900,2011-08-20,...,Voluntary Resignation,Better salary,Fully Meets,3.38,3,2,0,7,45,1.9
2,10003,Admin Offices,Office Coordinator,2,ADM-M3,LinkedIn,Male,1975-04-06,43500,2011-08-30,...,Active,NaN,Fully Meets,4.85,3,1,0,6,0,0.1
3,10004,Production,Production Technician II,2,PRD-M2,Indeed,Female,1974-09-08,48800,2011-09-23,...,Voluntary Resignation,Work hours / overtime,Fully Meets,3.98,4,1,0,4,14,0.8
4,10005,Sales,Account Executive,2,SLS-M2,Company Website,Female,1970-03-06,50600,2011-10-02,...,Voluntary Resignation,Dissatisfaction with management,Fully Meets,3.01,2,1,0,6,24,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,11596,Production,Production Technician I,1,PRD-M3,Google Search,Female,1990-12-05,39700,2026-09-25,...,Active,NaN,Fully Meets,4.37,4,1,0,9,14,0.0
1596,11597,Production,Production Technician II,2,PRD-M1,LinkedIn,Male,1987-08-05,42600,2026-09-26,...,Active,NaN,Fully Meets,3.89,3,0,0,6,9,0.0
1597,11598,Software Engineering,Junior Software Engineer,1,SWE-M3,Campus Recruiting,Male,1987-01-30,57900,2026-09-28,...,Active,NaN,Fully Meets,3.65,4,1,1,5,17,0.0
1598,11599,Sales,Sales Associate,1,SLS-M4,Company Website,Male,1988-12-20,39300,2026-09-28,...,Active,NaN,Fully Meets,4.18,3,1,0,7,13,0.0
1599,11600,Sales,Account Executive,2,SLS-M3,LinkedIn,Male,1978-06-01,46500,2026-09-29,...,Active,NaN,Fully Meets,3.92,3,2,1,3,11,0.0

In [10]:
df.head()

,EmpID,Department,Position,JobLevel,ManagerID,RecruitmentSource,Gender,DateofBirth,Salary,DateofHire,...,EmploymentStatus,TermReason,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,DaysLateLast30,Absences,OvertimeHoursPerMonth,YearsSinceLastPromotion
0,10001,Production,Production Technician II,2,PRD-M3,Company Website,Male,1976-01-04,45100,2011-07-06,...,Active,NaN,Fully Meets,3.89,4,2,0,8,19,2.4
1,10002,Production,Production Lead,4,PRD-M2,Google Search,Female,1974-12-25,57900,2011-08-20,...,Voluntary Resignation,Better salary,Fully Meets,3.38,3,2,0,7,45,1.9
2,10003,Admin Offices,Office Coordinator,2,ADM-M3,LinkedIn,Male,1975-04-06,43500,2011-08-30,...,Active,NaN,Fully Meets,4.85,3,1,0,6,0,0.1
3,10004,Production,Production Technician II,2,PRD-M2,Indeed,Female,1974-09-08,48800,2011-09-23,...,Voluntary Resignation,Work hours / overtime,Fully Meets,3.98,4,1,0,4,14,0.8
4,10005,Sales,Account Executive,2,SLS-M2,Company Website,Female,1970-03-06,50600,2011-10-02,...,Voluntary Resignation,Dissatisfaction with management,Fully Meets,3.01,2,1,0,6,24,2.3

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EmpID                    1600 non-null   int64
 1   Department               1600 non-null   str
 2   Position                 1600 non-null   str
 3   JobLevel                 1600 non-null   int64
 4   ManagerID                1600 non-null   str
 5   RecruitmentSource        1600 non-null   str
 6   Gender                   1600 non-null   str
 7   DateofBirth              1600 non-null   str
 8   Salary                   1600 non-null   int64
 9   DateofHire               1600 non-null   str
 10  DateofTermination        608 non-null    str
 11  EmploymentStatus         1600 non-null   str
 12  TermReason               608 non-null    str
 13  PerformanceScore         1600 non-null   str
 14  EngagementSurvey         1600 non-null   float64
 15  EmpSatisfaction          1600 non-null   int64
 16  SpecialProjectsCount     1600 non-null   int64
 17  DaysLateLast30           1600 non-null   int64
 18  Absences                 1600 non-null   int64
 19  OvertimeHoursPerMonth    1600 non-null   int64
 20  YearsSinceLastPromotion  1600 non-null   float64
dtypes: float64(2), int64(8), str(11)
memory usage: 262.6 KB

In [13]:
df["DateofHire"] = pd.to_datetime(df["DateofHire"])
df["DateofTermination"] = pd.to_datetime(df["DateofTermination"])
df["DateofBirth"] = pd.to_datetime(df["DateofBirth"])

In [15]:
df["tenure"] = df["DateofTermination"] - df["DateofHire"]
df["tenure"] = df["tenure"].fillna(pd.Timestamp("2026-09-30") - df["DateofHire"])
df["TenureYears"] = df["tenure"].dt.days / 365.25

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EmpID                    1600 non-null   int64
 1   Department               1600 non-null   str
 2   Position                 1600 non-null   str
 3   JobLevel                 1600 non-null   int64
 4   ManagerID                1600 non-null   str
 5   RecruitmentSource        1600 non-null   str
 6   Gender                   1600 non-null   str
 7   DateofBirth              1600 non-null   datetime64[us]
 8   Salary                   1600 non-null   int64
 9   DateofHire               1600 non-null   datetime64[us]
 10  DateofTermination        608 non-null    datetime64[us]
 11  EmploymentStatus         1600 non-null   str
 12  TermReason               608 non-null    str
 13  PerformanceScore         1600 non-null   str
 14  EngagementSurvey         1600 non-null   float64
 15  EmpSatisfaction          1600 non-null   int64
 16  SpecialProjectsCount     1600 non-null   int64
 17  DaysLateLast30           1600 non-null   int64
 18  Absences                 1600 non-null   int64
 19  OvertimeHoursPerMonth    1600 non-null   int64
 20  YearsSinceLastPromotion  1600 non-null   float64
 21  tenure                   1600 non-null   timedelta64[us]
 22  TenureYears              1600 non-null   float64
dtypes: datetime64[us](3), float64(3), int64(8), str(8), timedelta64[us](1)
memory usage: 287.6 KB

**Note**

Leaving out the 104 employees terminated for cause. They are Involuntary exits and a retention programme is not applicable to them, so including them would teach the model something false. That leaves 1496 rows, of which 504 resigned (33.7%)

In [17]:
df["EmploymentStatus"].value_counts()

EmploymentStatus
Active                   992
Voluntary Resignation    504
Terminated for Cause     104
Name: count, dtype: int64

In [18]:
attrition_df = df[
    df["EmploymentStatus"].isin([
        "Active",
        "Voluntary Resignation"
    ])
].copy()

In [19]:
attrition_df["EmploymentStatus"].value_counts()

EmploymentStatus
Active                   992
Voluntary Resignation    504
Name: count, dtype: int64

**Here’s how it works:**
1. The comparison checks each employee’s status and returns True or False.
2. .astype(int) converts True to 1 and False to 0.

In [20]:
attrition_df["Attrition"] = (
    attrition_df["EmploymentStatus"] == "Voluntary Resignation"
).astype(int)

In [21]:
attrition_df[["EmploymentStatus", "Attrition"]].value_counts()

EmploymentStatus       Attrition
Active                 0            992
Voluntary Resignation  1            504
Name: count, dtype: int64

In [22]:
X = attrition_df[
    ["EngagementSurvey", "EmpSatisfaction", "OvertimeHoursPerMonth"]
]

y = attrition_df["Attrition"]

In [24]:
X.shape

(1496, 3)

**Note:** 
test_size=0.2  - reserves 20% for testing.

random_state=42 - makes the split reproducible when you rerun it.

stratify=y  - When splitting the data, keep approximately the same proportion of 0s and 1s in the training and test sets.

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [28]:
print("Overall:")
print(y.value_counts(normalize=True))

print("\nTraining:")
print(y_train.value_counts(normalize=True))

print("\nTest:")
print(y_test.value_counts(normalize=True))

Overall:
Attrition
0    0.663102
1    0.336898
Name: proportion, dtype: float64

Training:
Attrition
0    0.663043
1    0.336957
Name: proportion, dtype: float64

Test:
Attrition
0    0.663333
1    0.336667
Name: proportion, dtype: float64

In [29]:
print("Training employees:", len(X_train))
print("Test employees:", len(X_test))

Training employees: 1196
Test employees: 300

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [31]:
print(scaler.mean_)

[ 3.79673077  3.75585284 11.29598662]

In [33]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [34]:
X_train_scaled[:5]

array([[-1.41447187, -1.96731346,  0.08940544],
       [ 0.00587779, -0.84688161,  1.9943146 ],
       [-1.19872256, -0.84688161,  0.34339332],
       [ 0.49131375,  1.39398211,  0.34339332],
       [-1.12680612, -1.96731346, -0.54556428]])

## Model Training

LogisticRegression() creates the model.

fit() trains it using the scaled features and the known outcomes in y_train

**Output:** In fitted attributes check the coef_: these are the weights the model learned for your three features.

In [35]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

## Predictions

In [36]:
y_pred = model.predict(X_test_scaled)

In [37]:
y_pred[:10]
#Model predicted 1 resignation

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

## Comparison

In [38]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison.head(10)

   Actual  Predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       1          0
5       0          0
6       1          0
7       1          1
8       0          0
9       1          0

In [39]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[184,  15],
       [ 74,  27]])

Findings:

- 184 active employees were correctly predicted as active.
- 15 active employees were incorrectly predicted as resigned: false positives.
- 74 employees who resigned were predicted as active: false negatives.
- 27 employees who resigned were correctly identified: true positives.
  
**Recall** - 27 ÷ 101 ≈ 0.267, so the model’s recall is approximately 26.7%.
  
**Precision** - The model predicted 42 employees would resign: 15 + 27. Of those, 27 actually resigned.

In [40]:
from sklearn.metrics import precision_score

precision_score(y_test, y_pred)

0.6428571428571429

In [41]:
model.predict_proba(X_test_scaled)[:5]

array([[0.61666603, 0.38333397],
       [0.63309129, 0.36690871],
       [0.8003338 , 0.1996662 ],
       [0.61840705, 0.38159295],
       [0.68882663, 0.31117337]])

In [45]:
# Get the probability of resignation for each test employee
prob_resigned = model.predict_proba(X_test_scaled)[:, 1]

In [46]:
# Predict resignation when the probability is 40% or higher
y_pred_40 = (prob_resigned >= 0.40).astype(int)

# Compare predictions with actual outcomes
confusion_matrix(y_test, y_pred_40)

array([[153,  46],
       [ 55,  46]])

In [47]:
# Predict 1 if the probability is 30% or higher; otherwise 0
y_pred_30 = (prob_resigned >= 0.30).astype(int)

# Compare the new predictions with the actual outcomes
confusion_matrix(y_test, y_pred_30)

array([[ 97, 102],
       [ 27,  74]])

# Learnings:

Logistic regression learned a weight for each feature and used the features together to estimate a probability of resignation.
- model.fit() trained the model.
- model.predict_proba() showed the probabilities.
- model.predict() converted those probabilities into predicted classes, 0 or 1.

The confusion matrix compared predictions with actual outcomes.

| Threshold | Recall | Precision |
|---|---:|---:|
| 30% | 73.3% | 42.0% |
| 40% | 45.5% | 50.0% |
| 50% | 26.7% | 64.3% |

Lowering the threshold identified more leavers but also produced more false alarms. The threshold should reflect the purpose and available resources.

**Note for future projects:** choose the threshold using validation data, then evaluate it on a separate test set. Here I explored thresholds on the test set to learn how they work.